apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:            # Especifica o tipo de volume como hostPath
    path: /mnt/data    # Caminho no host onde os dados serão armazenados
